version: '3.7'

services:
  python:
    container_name: Python
    build:
      context: .
      dockerfile: Docker/Dockerfile
    command: python -m flask run --host '0.0.0.0' --port '5000'
    environment:
      FLASK_APP: .
      FLASK_ENV: development
      # FLASK_DEBUG: 1
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - ./flask/:/app
    networks:
      - python

  db:
    container_name: Python-MySQL
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    command: '--default-authentication-plugin=mysql_native_password'
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    volumes:
      - python-db:/var/lib/mysql
    networks:
      - python

  phpmyadmin:
    container_name: Python-MyAdmin
    image: phpmyadmin/phpmyadmin:5.0
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOSTS: db
    ports:
      - 8888:80
    links:
      - db
    networks:
      - python

networks:
  python:
volumes:
  python-db:
